{"uid":"f7d0f60d72f1b505","name":"Check App build and running","fullName":"Check App build and running","historyId":"6ce4903225b1ea8c4f8b451f2a617597","time":{"start":1675358116706,"stop":1675358117382,"duration":676},"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3001/remoteEntry.js)\nwhile loading \"./Button\" from webpack/container/reference/component-app\nwhile loading \"./Dialog\" from webpack/container/reference/component-app\nwhile loading \"./ToolTip\" from webpack/container/reference/component-app\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"ScriptExternalLoadError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3001/remoteEntry.js)\nwhile loading \"./Button\" from webpack/container/reference/component-app\nwhile loading \"./Dialog\" from webpack/container/reference/component-app\nwhile loading \"./ToolTip\" from webpack/container/reference/component-app\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at webpack/container/reference/component-app (http://localhost:3002/main.js:11:25)\n    at __webpack_require__ (http://localhost:3002/main.js:72:41)\n    at handleFunction (http://localhost:3002/main.js:248:31)\n    at <unknown> (http://localhost:3002/main.js:267:15)\n    at Array.forEach (<anonymous>)\n    at __webpack_require__.f.remotes (http://localhost:3002/main.js:230:36)\n    at <unknown> (http://localhost:3002/main.js:113:40)\n    at Array.reduce (<anonymous>)\n    at __webpack_require__.e (http://localhost:3002/main.js:112:67)\n    at <unknown> (http://localhost:3002/main.js:424:21)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3001/remoteEntry.js)\nwhile loading \"./Button\" from webpack/container/reference/component-app\nwhile loading \"./Dialog\" from webpack/container/reference/component-app\nwhile loading \"./ToolTip\" from webpack/container/reference/component-app\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","statusTrace":"ScriptExternalLoadError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > Loading script failed.\n(error: http://localhost:3001/remoteEntry.js)\nwhile loading \"./Button\" from webpack/container/reference/component-app\nwhile loading \"./Dialog\" from webpack/container/reference/component-app\nwhile loading \"./ToolTip\" from webpack/container/reference/component-app\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application\n    at webpack/container/reference/component-app (http://localhost:3002/main.js:11:25)\n    at __webpack_require__ (http://localhost:3002/main.js:72:41)\n    at handleFunction (http://localhost:3002/main.js:248:31)\n    at <unknown> (http://localhost:3002/main.js:267:15)\n    at Array.forEach (<anonymous>)\n    at __webpack_require__.f.remotes (http://localhost:3002/main.js:230:36)\n    at <unknown> (http://localhost:3002/main.js:113:40)\n    at Array.reduce (<anonymous>)\n    at __webpack_require__.e (http://localhost:3002/main.js:112:67)\n    at <unknown> (http://localhost:3002/main.js:424:21)","steps":[{"name":"\"before each\" hook","time":{"start":1675358116706,"stop":1675358117063,"duration":357},"status":"passed","steps":[{"name":"visit http://localhost:3002","time":{"start":1675358116870,"stop":1675358117062,"duration":192},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[],"parameters":[],"stepsCount":1,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":true},{"name":"get h1","time":{"start":1675358117066,"stop":1675358117380,"duration":314},"status":"failed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false},{"name":"uncaught exception ScriptExternalLoadError: Loading script failed.\n(error: http://localhost:3001/remoteEntry.js)\nwhile loading \"./Button\" from webpack/container/reference/component-app\nwhile loading \"./Dialog\" from webpack/container/reference/component-app\nwhile loading \"./ToolTip\" from webpack/container/reference/component-app","time":{"start":1675358117380,"stop":1675358117380,"duration":0},"status":"failed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"attachments":[{"uid":"2f196880ac12a8c4","name":"e2e/checkApplication.cy.ts:2023-02-02T17:15:16.258Z","source":"2f196880ac12a8c4.png","type":"image/png","size":81816},{"uid":"c31b4fff1e6c65ac","name":"e2e/checkApplication.cy.ts:2023-02-02T17:15:17.091Z:attempt-1","source":"c31b4fff1e6c65ac.png","type":"image/png","size":159507},{"uid":"24f73d289ffe332b","name":"video recording","source":"24f73d289ffe332b.mp4","type":"video/mp4","size":1788761}],"parameters":[],"stepsCount":4,"attachmentsCount":3,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[],"labels":[{"name":"suite","value":"Check App1"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"7a8b6b7778f6edfa","status":"skipped","statusDetails":"Test ignored","time":{"start":1675358030888,"stop":1675358030890,"duration":2}}],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"f7d0f60d72f1b505.json","parameterValues":[]}